# Generated by Django 4.0.3 on 2022-12-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('asunto', models.CharField(max_length=200, null=True)),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
    ]
